apiVersion: apps/v1
kind: Deployment
metadata:
  name: insert-notification
  namespace: smtrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insert-notification
  template:
    metadata:
      labels:
        app: insert-notification
    spec:
      containers:
      - name: insert-notification
        image: siamatic/smtrack-insert-notification:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 100m
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: DATABASE_URL
        - name: RABBITMQ
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ
        - name: INFLUXDB_URI
          valueFrom:
            configMapKeyRef:
              name: influxdb-config
              key: INFLUXDB_URI
        - name: INFLUXDB_ORG
          valueFrom:
            configMapKeyRef:
              name: influxdb-config
              key: INFLUXDB_ORG
        - name: INFLUXDB_BUCKET
          valueFrom:
            configMapKeyRef:
              name: influxdb-config
              key: INFLUXDB_BUCKET
        - name: INFLUXDB_TOKEN
          valueFrom:
            configMapKeyRef:
              name: influxdb-config
              key: INFLUXDB_TOKEN
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: NODE_ENV
