export type Probe = {
  channel: string,
  createAt: string,
  device: Device,
  doorAlarmTime: string,
  doorQty: number,
  doorSound: boolean,
  firstDay: string,
  firstTime: string,
  humiAdj: number,
  humiMax: number,
  humiMin: number,
  id: string,
  muteAlarmDuration: string,
  muteDoorAlarmDuration: string,
  name: string,
  notiDelay: number,
  notiMobile: boolean,
  notiRepeat: number,
  notiToNormal: boolean,
  position: string,
  secondDay: string,
  secondTime: string,
  sn: string,
  stampTime: string,
  tempAdj: number,
  tempMax: number,
  tempMin: number,
  thirdDay: string,
  thirdTime: string,
  type: string,
  updateAt: string
}

export type Log = {
  battery: number,
  createAt: string,
  door1: boolean,
  door2: boolean,
  door3: boolean,
  expire: string,
  extMemory: boolean,
  humidity: number,
  humidityDisplay: number,
  id: string,
  internet: boolean,
  plug: boolean,
  probe: string,
  sendTime: string,
  serial: string,
  temp: number,
  tempDisplay: number,
  tempInternal: number,
  updateAt: string
}

export type Device = {
  createAt: string,
  deviceId: string,
  firmware: string,
  hospital: string,
  hospitalName: string,
  id: string,
  installDate: string,
  location: string,
  log: Log[],
  name: string,
  online: boolean,
  position: string,
  positionPic: string,
  remark: string,
  seq: number,
  staticName: string,
  status: boolean,
  tag: string,
  token: string,
  updateAt: string,
  ward: string,
  wardName: string
}