name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: siamatic/smtrack-insert-notification:1.0.1
    steps:
    - uses: actions/checkout@v4
    - name: Create service account key file
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > ./temp-alarm-firebase-adminsdk.json
        cat firebase-key.json
        cat firebase-key.json | jq
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}
    - name: Update Kubernetes manifest with new image
      run: |
        sed -i "s|image: .*|image: ${{ env.IMAGE_NAME }}|" k8s/deploy.yaml
        git config user.name "FangLy"
        git config user.email "thefangsni@gmail.com"
        git add k8s/deploy.yaml
        git commit -m "${{ env.IMAGE_NAME }}"
        git push
    - name: Send success message to slack
      id: slack
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "text": "GitHub Action build ${{ env.IMAGE_NAME }} result: ${{ job.status }} 🖕🖕🖕🖕",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build ${{ env.IMAGE_NAME }} result: ${{ job.status }} 🖕🖕🖕🖕"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
